


```{r}
library(keras)
library(EBImage)
setwd("/Users/akashsetti/Desktop/stuff")
pic1 <- c('p1.jpg', 'p2.jpg', 'p3.jpg', 'p4.jpg', 'p5.jpg',
          'c1.jpg', 'c2.jpg', 'c3.jpg', 'c4.jpg', 'c5.jpg',
          'b1.jpg', 'b2.jpg', 'b3.jpg', 'b4.jpg', 'b5.jpg')
train <- list()
for (i in 1:15) {train[[i]] <- readImage(pic1[i])}

pic2 <- c('p6.jpg', 'c6.jpg', 'b6.jpg')
test <- list()
for (i in 1:3) {test[[i]] <- readImage(pic2[i])}

```

```{r}
# plot(train[[12]])
par(mfrow = c(3,5))
for (i in 1:15) plot(train[[i]])
par(mfrow = c(1,1))
```


we have to resize
```{r}
# str(train)
for (i in 1:15) {train[[i]] <- resize(train[[i]], 100, 100)}
for (i in 1:3) {test[[i]] <- resize(test[[i]], 100, 100)}

train <- combine(train)
x <- tile(train, 5)
display(x, title = 'Train Pics')


test <- combine(test)
y <- tile(test, 3)
display(y, title = 'Test Pics')

# reorder the dimentsions

train <- aperm(train, c(4,1,2,3))
test <- aperm(test, c(4,1,2,3))
```



```{r}
# Response
trainy <- c(0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2)
testy <- c(0, 1, 2)
```


```{r}
trainLabels <- to_categorical(trainy)
testLabels <- to_categorical(testy)
```


```{r}
set.seed(1)
model <- keras_model_sequential()
model %>%
  layer_conv_2d(filters = 32,
                kernel_size = c(3,3),
                activation = 'relu',
                input_shape = c(100,100,3)) %>%
  layer_conv_2d(filters = 32,
                kernel_size = c(3,3),
                activation = 'relu') %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  layer_dropout(rate = 0.25) %>%
  layer_conv_2d(filters = 64,
                kernel_size = c(3,3),
                activation = 'relu') %>%
  layer_conv_2d(filters = 64,
                kernel_size = c(3,3),
                activation = 'relu') %>%
  layer_max_pooling_2d(pool_size = c(2,2)) %>%
  layer_dropout(rate = 0.25) %>%
  layer_flatten() %>%
  layer_dense(units = 256, activation = 'relu') %>%
  layer_dropout(rate = 0.25) %>%
  layer_dense(units = 3, activation = 'softmax') %>%
  
  compile(loss = 'categorical_crossentropy',
          optimizer = optimizer_sgd(lr = 0.01, 
                                    decay = 1e-6,
                                    momentum = 0.9,
                                    nesterov = T),
          metrics = c('accuracy'))
```


```{r}
summary(model)
```


Fit the Model
```{r}
history <- model %>%
  fit(train,
      trainLabels,
      epochs = 60,
      batch_size = 32,
      validation_split = 0.2)

```


```{r}
model %>% evaluate(train, trainLabels)
pred <- model %>% predict(train) %>% k_argmax()
# Y_pred = round(pred)
# CM = table(Y_pred, trainy)



# predArr <- np_array(pred)
# predArr <- reticulate::py_to_r(predArr) 
# accuracy <- function(pred, truth)
#   mean(drop(pred) == drop(truth))

# accuracy(predArr, train) 

# table(Predicted = pred, Actual = trainy)
```


